# Generated by Django 2.2.13 on 2021-01-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='comments',
            field=models.CharField(max_length=1000, verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='film',
            name='stars',
            field=models.IntegerField(verbose_name='星级'),
        ),
    ]
