# Generated by Django 2.2.13 on 2021-01-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210131_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Films',
        ),
    ]
